# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# Check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.3.0
maven_group=rocks.theatomicoption

# Dependencies
fabric_api_version=0.153.0+26.1.2
jei_version=29.12.0.39
rei_version=26.1.819
architectury_version=20.0.6
cloth_config_version=26.1.154
